json.id @quote.id
json.contact_id @quote.contact_id
json.generated_by_id @quote.generated_by_id
json.zoho_deal_id @quote.zoho_deal_id
json.trigger_source @quote.trigger_source
json.status @quote.status
json.error_message @quote.error_message
json.nombre @quote.nombre
json.lote @quote.lote
json.desarrollo @quote.desarrollo
json.plazos @quote.plazos
json.meses_sin_intereses @quote.meses_sin_intereses
json.superficie @quote.superficie
json.precio_m2 @quote.precio_m2
json.fecha_entrega @quote.fecha_entrega
json.monto_base @quote.monto_base
json.descuento_aplicado @quote.descuento_aplicado
json.monto @quote.monto
json.enganche_pct @quote.enganche_pct
json.enganche_monto @quote.enganche_monto
json.interes_pct @quote.interes_pct
json.pago_mensual @quote.pago_mensual
json.precio_total @quote.precio_total
json.precio_m2_final @quote.precio_m2_final
json.schedule @quote.schedule
json.pdf_attached @quote.pdf.attached?
json.created_at @quote.created_at
